### PR TITLE
Added support for FramaTube.

### PR DESCRIPTION
**Pull request by comete-upn**
Thanks for the plugin, it saves us a bunch of time.
We added support for FramaTube, as requested by our teachers.
We're hoping it's to your liking.

### CODE REVIEW

**Comment by comete-upn** [comment]
Sorry: not really safe. A better code is coming soon…

**Comment by comete-upn** [comment]
That should do it. Sorry for the multiple posting.

**Comment by deedey** [comment]
Hi! @comete-upn 
framatube.org do not exist:
[Read this](https://framablog.org/2017/11/22/framatube-aidez-nous-a-briser-lhegemonie-de-youtube/)

**Comment by comete-upn** [comment]
Hello @deedey,
Yes, we understand that. FramaTube is a fantastic frontage to the PeerTube video platform system nonetheless. And as we try to spur our teachers to use FOSS using Framasoft and all its projects, it seemed like a good match.

**Comment by deedey** [comment]
Hi @comete-upn ,
Thank you for this reply.
I think so, but I think also that FramaTube has not a really chance to be operational in the near future because it requires a huge cost to implement it. 
Be sure that we also try every day to spur our teachers to use all the tools offered by FramaSoft, but just tools which gives them a real productivity.
Regards

**Pull request closed without merging**
